import type { Metadata } from "next";
import "./globals.css";
import Nav from "./_components/Nav";

// import { Geist, Geist_Mono } from "next/font/google";

// add a class to body and insert a global font?
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  // add a class to body and insert a global font?
  // <body className={`${geistSans.variable} ${geistMono.variable}`}>

  return (
    <html lang="en">
      <body>
        <Nav />
        <main>{children}</main>
        <footer>© JD Nafziger, 2025</footer>
      </body>
    </html>
  );
}
