
import fs from 'fs'
import path from 'path'
import { Board, Square } from '../interfaces/Board';

// Run this file with 
// npx tsx frontend/app/lib/data/generateBoard.ts

// this will create or overwrite this file name:
const fileName = 'emptyBoard.ts'

saveFile(fileName);

function getStartingState(): Square[] {
	const letters = 'abcdefgh'
	const numbers = '12345678'

	const board: Board = [];
	let counter: number = 0;
	let isBlack: boolean = true;
	let letter: string;
	let number: string;
	for (let i = 0; i < 8; i++) {     // from 1 to 8 => bottom to top
		number = numbers[i]
		for (let j = 0; j < 8; j++) { // from a to h => left to right
			letter = letters[j]
			board.push({
				id: counter,
				coordinate: `${letter}${number}`, //chessboard coordinate
				x: j, //x coordinate
				y: i, //y coordinate
				piece: null,
				// underAttackFromWhite: false, // no longer in use
				// underAttackFromBlack: false, // no longer in use
				isBlack: isBlack
			})
			counter++;
			isBlack = !isBlack
		}
		isBlack = !isBlack //on next row, start with opposite color
	}
	return board
}

function saveFile(fileName) {
	const array = getStartingState();
	const board = JSON.stringify(array, null, 2);

	const fileContents = `// This file is auto-generated by generateBoard.ts
import { Board } from '../interfaces/board';

export const blankBoard: Board = ${board}`


	console.log(`Saving content to ${fileName} ...`)
	fs.writeFile(path.resolve(__dirname, `./${fileName}`), fileContents, err => {
		if (err) {
			console.error("Error writing file:", err);
		}
	});
}

